# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/lucas.andrade/bluedragon/synth-vivado/optimsoc_examples_compute_tile_nexys4ddr_0.cache/wt [current_project]
set_property parent.project_path /home/lucas.andrade/bluedragon/synth-vivado/optimsoc_examples_compute_tile_nexys4ddr_0.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/lucas.andrade/bluedragon/synth-vivado/optimsoc_examples_compute_tile_nexys4ddr_0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog
  /home/lucas.andrade/bluedragon/src/optimsoc_bootrom_bootrom_0/verilog
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_dma_0/rtl/dma
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_dma_0/rtl
  /home/lucas.andrade/bluedragon/synth-vivado
} [current_fileset]
set_property generic NUM_CORES=4 [current_fileset]
read_verilog -library xil_defaultlib -sv {
  /home/lucas.andrade/bluedragon/src/glip_common_channel_0/glip_channel.sv
  /home/lucas.andrade/bluedragon/src/glip_common_scaler_0/verilog/glip_downscale.sv
  /home/lucas.andrade/bluedragon/src/glip_common_scaler_0/verilog/glip_upscale.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_blocks_tracesample_0/common/osd_tracesample.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_interfaces_dii_channel_0/common/dii_channel.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_interfaces_dii_channel_0/common/dii_channel_flat.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_interfaces_mor1kx_trace_exec_0/or1k/mor1kx_trace_exec.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_base_constants_0/optimsoc_constants.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_base_functions_0/optimsoc_functions.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_debug_system_mam_wb_adapter_0/verilog/mam_wb_adapter.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_fifo_fifo_dualclock_standard_0/verilog/fifo_dualclock_standard.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_fifo_fifo_singleclock_standard_0/verilog/fifo_singleclock_standard.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_wb_interconnect_decode_0/verilog/wb_decode.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_wb_interconnect_mux_0/verilog/wb_mux.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_wb_interconnect_mux_0/verilog/wb_interconnect_arb_rr.v
  /home/lucas.andrade/bluedragon/src/wallento_arbiter_rr_0/arb_rr.sv
  /home/lucas.andrade/bluedragon/src/wallento_svchannels_nasti_0/rtl/verilog/nasti_channel.sv
  /home/lucas.andrade/bluedragon/src/wallento_svchannels_wishbone_0/rtl/verilog/wb_channel.sv
  /home/lucas.andrade/bluedragon/src/wallento_wb2axi_wb2axi_0/src/wb2axi.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_blocks_buffer_0/common/dii_buffer.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_blocks_buffer_0/common/osd_fifo.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_blocks_eventpacket_0/common/osd_event_packetization.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_blocks_timestamp_0/common/osd_timestamp.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_interconnect_debug_ring_0/common/debug_ring.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_interconnect_debug_ring_0/common/debug_ring_expand.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_interconnect_debug_ring_0/common/ring_router_demux.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_interconnect_debug_ring_0/common/ring_router.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_interconnect_debug_ring_0/common/ring_router_mux.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_interconnect_debug_ring_0/common/ring_router_mux_rr.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_interconnect_debug_ring_0/common/ring_router_gateway.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_interconnect_debug_ring_0/common/ring_router_gateway_demux.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_interconnect_debug_ring_0/common/ring_router_gateway_mux.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_modules_dem_uart_wb_0/common/osd_dem_uart_wb.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_modules_dem_uart_wb_0/common/osd_dem_uart_16550.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_modules_dem_uart_wb_0/common/osd_dem_uart.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_modules_mam_0/common/osd_mam.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_base_config_0/optimsoc_config.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_core_mor1kx_module_0/verilog/mor1kx_module.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_fifo_fifo_dualclock_fwft_0/verilog/fifo_dualclock_fwft.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_fifo_fifo_singleclock_fwft_0/verilog/fifo_singleclock_fwft.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_dma_0/rtl/dma/lisnoc_dma.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_dma_0/rtl/dma/lisnoc_dma_target.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_dma_0/rtl/dma/lisnoc_dma_initiator.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_dma_0/rtl/dma/lisnoc_dma_initiator_nocreq.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_dma_0/rtl/dma/lisnoc_dma_initiator_nocresp.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_dma_0/rtl/dma/lisnoc_dma_request_table.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_dma_0/rtl/infrastructure/lisnoc_packet_buffer.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_router_0/rtl/router/lisnoc_router_arbiter.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_router_0/rtl/router/lisnoc_router_output_arbiter.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_router_0/rtl/router/lisnoc_router_arbiter_prio.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_mp_buffer_0/verilog/mpbuffer.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_mp_buffer_0/verilog/mpbuffer_wb.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_mp_buffer_0/verilog/mpbuffer_endpoint.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_noc_mux_0/verilog/noc_mux.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_sram_sp_plain_0/verilog/wb_sram_sp.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_sram_sp_plain_0/verilog/wb2sram.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_sram_sp_plain_0/verilog/sram_sp.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_sram_sp_plain_0/verilog/sram_sp_impl_plain.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_wb_interconnect_bus_0/verilog/wb_bus_b3.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_blocks_eventpacket_fixedwidth_0/common/osd_event_packetization_fixedwidth.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_blocks_regaccess_0/common/osd_regaccess.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_blocks_regaccess_0/common/osd_regaccess_layer.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_blocks_regaccess_0/common/osd_regaccess_demux.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_modules_him_0/common/osd_him.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_modules_mam_wb_0/wishbone/osd_mam_wb.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_modules_mam_wb_0/wishbone/osd_mam_wb_if.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_noc_buffer_0/verilog/noc_buffer.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_noc_demux_0/verilog/noc_demux.sv
  /home/lucas.andrade/bluedragon/src/wallento_boards_nexys4ddr_0/rtl/verilog/nexys4ddr.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_modules_ctm_mor1kx_0/or1k/mor1kx/osd_ctm_mor1kx.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_modules_ctm_mor1kx_0/common/osd_ctm.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_modules_scm_0/common/osd_scm.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_modules_stm_mor1kx_0/or1k/mor1kx/osd_stm_mor1kx.sv
  /home/lucas.andrade/bluedragon/src/opensocdebug_modules_stm_mor1kx_0/common/osd_stm.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_networkadapter_networkadapter_ct_0/verilog/networkadapter_ct.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_networkadapter_networkadapter_ct_0/verilog/networkadapter_conf.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_debug_debug_interface_0/verilog/debug_interface.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_tile_compute_tile_dm_0/verilog/compute_tile_dm.sv
  /home/lucas.andrade/bluedragon/src/optimsoc_examples_compute_tile_nexys4ddr_0/rtl/verilog/compute_tile_dm_nexys4.sv
}
read_verilog -library xil_defaultlib {
  /home/lucas.andrade/bluedragon/src/glip_common_credit_0/verilog/creditor.v
  /home/lucas.andrade/bluedragon/src/glip_common_credit_0/verilog/debtor.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_branch_predictor_gshare.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_branch_predictor_simple.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_branch_predictor_saturation_counter.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_branch_prediction.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_bus_if_wb32.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_cache_lru.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_cfgrs.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_cpu_cappuccino.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_cpu_espresso.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_cpu_prontoespresso.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_cpu.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_ctrl_cappuccino.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_ctrl_espresso.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_ctrl_prontoespresso.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_dcache.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_decode_execute_cappuccino.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_decode.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_dmmu.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_execute_alu.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_execute_ctrl_cappuccino.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_fetch_cappuccino.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_fetch_espresso.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_fetch_prontoespresso.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_fetch_tcm_prontoespresso.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_icache.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_immu.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_lsu_cappuccino.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_lsu_espresso.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_pcu.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_pic.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_rf_cappuccino.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_rf_espresso.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_simple_dpram_sclk.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_store_buffer.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_ticktimer.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_true_dpram_sclk.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_wb_mux_cappuccino.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/mor1kx_wb_mux_espresso.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/pfpu32/pfpu32_addsub.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/pfpu32/pfpu32_cmp.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/pfpu32/pfpu32_f2i.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/pfpu32/pfpu32_i2f.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/pfpu32/pfpu32_muldiv.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/pfpu32/pfpu32_rnd.v
  /home/lucas.andrade/bluedragon/src/mor1kx_5.0/rtl/verilog/pfpu32/pfpu32_top.v
  /home/lucas.andrade/bluedragon/src/optimsoc_bootrom_bootrom_0/verilog/bootrom.v
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_blocks_0/rtl/lisnoc_arb_rr.v
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_dma_0/rtl/dma/lisnoc_dma_initiator_wbreq.v
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_dma_0/rtl/dma/lisnoc_dma_wbinterface.v
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_router_0/rtl/router/lisnoc_router.v
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_router_0/rtl/router/lisnoc_fifo.v
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_router_0/rtl/router/lisnoc_router_input.v
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_router_0/rtl/router/lisnoc_router_input_route.v
  /home/lucas.andrade/bluedragon/src/optimsoc_lisnoc_router_0/rtl/router/lisnoc_router_output.v
  /home/lucas.andrade/bluedragon/src/glip_backend_uart_0/verilog/glip_uart_control_egress.v
  /home/lucas.andrade/bluedragon/src/glip_backend_uart_0/verilog/glip_uart_control_ingress.v
  /home/lucas.andrade/bluedragon/src/glip_backend_uart_0/verilog/glip_uart_control.v
  /home/lucas.andrade/bluedragon/src/glip_backend_uart_0/verilog/glip_uart_receive.v
  /home/lucas.andrade/bluedragon/src/glip_backend_uart_0/verilog/glip_uart_toplevel.v
  /home/lucas.andrade/bluedragon/src/glip_backend_uart_0/verilog/glip_uart_transmit.v
}
read_ip -quiet /home/lucas.andrade/bluedragon/src/wallento_boards_nexys4ddr-ddr_0/ip/mig_7series/mig_7series.xci
set_property used_in_implementation false [get_files -all /home/lucas.andrade/bluedragon/src/wallento_boards_nexys4ddr-ddr_0/ip/mig_7series/mig_7series/user_design/constraints/mig_7series_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lucas.andrade/bluedragon/src/wallento_boards_nexys4ddr-ddr_0/ip/mig_7series/mig_7series/user_design/constraints/mig_7series.xdc]

read_ip -quiet /home/lucas.andrade/bluedragon/src/wallento_boards_nexys4ddr-clk_ddr_0/ip/clk_gen_ddr/clk_gen_ddr.xci
set_property used_in_implementation false [get_files -all /home/lucas.andrade/bluedragon/src/wallento_boards_nexys4ddr-clk_ddr_0/ip/clk_gen_ddr/clk_gen_ddr_board.xdc]
set_property used_in_implementation false [get_files -all /home/lucas.andrade/bluedragon/src/wallento_boards_nexys4ddr-clk_ddr_0/ip/clk_gen_ddr/clk_gen_ddr.xdc]
set_property used_in_implementation false [get_files -all /home/lucas.andrade/bluedragon/src/wallento_boards_nexys4ddr-clk_ddr_0/ip/clk_gen_ddr/clk_gen_ddr_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/lucas.andrade/bluedragon/src/wallento_boards_nexys4ddr_0/data/pins.xdc
set_property used_in_implementation false [get_files /home/lucas.andrade/bluedragon/src/wallento_boards_nexys4ddr_0/data/pins.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top compute_tile_dm_nexys4 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef compute_tile_dm_nexys4.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file compute_tile_dm_nexys4_utilization_synth.rpt -pb compute_tile_dm_nexys4_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
